import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * A block of a document generated from the code (decision 177): it sits between a marker naming its tool and
 * `<!-- /generado -->`, the tool rewrites it, and a test compares it with a fresh rendering so the document cannot
 * drift from the code.
 */
const END = '<!-- /generado -->';

export function beginMarker(tool: string): string {
  return `<!-- generado por ${tool}: no editar a mano -->`;
}

/** The block `tool` generated in a document, markers included, or null when the document has none. */
export function generatedBlock(md: string, tool: string): string | null {
  const a = md.indexOf(beginMarker(tool));
  if (a < 0) return null;
  const b = md.indexOf(END, a);
  return b < 0 ? null : md.slice(a, b + END.length);
}

/** A rendered block: the markers of `tool` around the body. */
export function wrapGenerated(tool: string, body: string): string {
  return `${beginMarker(tool)}\n${body}\n${END}`;
}

/** The command line of a generator: rewrite the block of `doc`, or with `--check` fail when it is stale. */
export function writeGenerated(doc: string, tool: string, block: string): void {
  const path = join(process.cwd(), doc);
  const md = readFileSync(path, 'utf8');
  const current = generatedBlock(md, tool);
  if (!current) throw new Error(`${doc} has no block generated by ${tool}`);
  if (process.argv.includes('--check')) {
    if (current !== block) {
      process.stderr.write(
        `${doc}: the block generated by ${tool} is stale; run npx tsx ${tool}\n`,
      );
      process.exit(1);
    }
    return;
  }
  writeFileSync(path, md.replace(current, block));
  process.stdout.write(`wrote the block generated by ${tool} in ${doc}\n`);
}
