import { Structure, Tissue } from './tissue';

/**
 * One colour per structure of the model, shared by the live cut map of the navigator (`CutMapView`) and the
 * offline slice maps (`tools/offline/render/slice-map.ts`), so a structure looks the same wherever the model
 * is drawn without acoustics. Left-heart blood is dark red, right-heart blood dark blue; the myocardium keeps
 * the same split (LV walls warm, RV wall cool); valves are yellow (mitral), green (tricuspid), magenta (aortic)
 * and cyan (pulmonary); bone is near white and lung olive.
 */
export type Rgb = readonly [number, number, number];

export const STRUCTURE_RGB: Partial<Record<Structure, Rgb>> = {
  [Structure.LvCavity]: [58, 22, 28],
  [Structure.LvWallSeptal]: [200, 80, 80],
  [Structure.LvWallLateral]: [230, 120, 120],
  [Structure.LvWallAnterior]: [210, 100, 100],
  [Structure.LvWallInferior]: [190, 90, 90],
  [Structure.LvApex]: [250, 150, 150],
  [Structure.PapillaryMuscle]: [255, 200, 120],
  [Structure.RvCavity]: [24, 34, 74],
  [Structure.RvWall]: [90, 110, 220],
  [Structure.Rvot]: [36, 40, 92],
  [Structure.LaCavity]: [78, 30, 40],
  [Structure.RaCavity]: [32, 44, 92],
  [Structure.MitralAnterior]: [255, 255, 120],
  [Structure.MitralPosterior]: [255, 230, 80],
  [Structure.TricuspidValve]: [160, 255, 160],
  [Structure.AorticValve]: [255, 140, 255],
  [Structure.AorticRoot]: [150, 48, 48],
  [Structure.Lvot]: [70, 30, 36],
  [Structure.PulmonaryValve]: [120, 255, 255],
  [Structure.InteratrialSeptum]: [200, 200, 120],
  [Structure.MitralAnnulus]: [255, 255, 255],
  [Structure.TricuspidAnnulus]: [220, 255, 220],
  [Structure.Chordae]: [255, 255, 200],
  [Structure.Pericardium]: [130, 130, 130],
  [Structure.PericardialEffusion]: [40, 90, 130],
  [Structure.ModeratorBand]: [255, 170, 60],
  [Structure.LaAppendage]: [110, 44, 70],
  [Structure.PulmonaryVein]: [96, 34, 42],
  [Structure.CoronarySinus]: [60, 30, 80],
  [Structure.PulmonaryArtery]: [50, 56, 130],
  [Structure.RvPapillary]: [255, 170, 100],
  [Structure.Svc]: [38, 50, 100],
  [Structure.Ivc]: [40, 66, 110],
  [Structure.HepaticVein]: [60, 80, 120],
  [Structure.Diaphragm]: [236, 226, 196],
  [Structure.EpicardialFat]: [205, 175, 95],
  [Structure.LaWall]: [200, 90, 140],
  [Structure.RaWall]: [120, 90, 160],
  [Structure.DescendingAorta]: [150, 48, 48],
  [Structure.ChestWall]: [150, 118, 92],
  [Structure.Rib]: [235, 235, 240],
  [Structure.Sternum]: [220, 220, 230],
  [Structure.Lung]: [72, 76, 52],
  [Structure.Liver]: [118, 72, 52],
  [Structure.Spine]: [240, 240, 240],
};

/** Colour of a thorax sample that carries no structure id (offline maps classify tissue too). */
export const TISSUE_RGB: Partial<Record<Tissue, Rgb>> = {
  [Tissue.Bone]: [240, 240, 240],
  [Tissue.Cartilage]: [200, 200, 220],
  [Tissue.Lung]: [72, 76, 52],
  [Tissue.Liver]: [118, 72, 52],
  [Tissue.Muscle]: [150, 70, 70],
  [Tissue.Fat]: [220, 200, 120],
  [Tissue.Skin]: [230, 190, 160],
  [Tissue.Spine]: [255, 255, 255],
  [Tissue.VesselWall]: [170, 60, 60],
  [Tissue.Blood]: [20, 20, 20],
  [Tissue.Fluid]: [30, 60, 90],
};

/** Short names the cut map writes over the structures the plane passes through (Spanish, as the HUD). */
export const CUT_MAP_LABELS: Partial<Record<Structure, string>> = {
  [Structure.LvCavity]: 'VI',
  [Structure.LvWallSeptal]: 'septo',
  [Structure.LvWallLateral]: 'pared lateral',
  [Structure.LvWallAnterior]: 'pared anterior',
  [Structure.LvWallInferior]: 'pared inferior e inferolateral',
  [Structure.LvApex]: 'ápex',
  [Structure.RvCavity]: 'VD',
  [Structure.RvWall]: 'pared VD',
  [Structure.LaCavity]: 'AI',
  [Structure.RaCavity]: 'AD',
  [Structure.MitralAnterior]: 'VM ant',
  [Structure.MitralPosterior]: 'VM post',
  [Structure.AorticValve]: 'VAo',
  [Structure.TricuspidValve]: 'VT',
  [Structure.AorticRoot]: 'Ao',
  [Structure.Lvot]: 'TSVI',
  [Structure.Rvot]: 'TSVD',
  [Structure.PapillaryMuscle]: 'MP',
  [Structure.Pericardium]: 'pericardio',
  [Structure.PericardialEffusion]: 'derrame',
  [Structure.DescendingAorta]: 'Ao desc',
  [Structure.Ivc]: 'VCI',
  [Structure.Rib]: 'costilla',
  [Structure.Sternum]: 'esternón',
  [Structure.Lung]: 'pulmón',
  [Structure.Liver]: 'hígado',
  [Structure.Spine]: 'columna',
  [Structure.InteratrialSeptum]: 'TIA',
  [Structure.PulmonaryValve]: 'VP',
  [Structure.ModeratorBand]: 'banda mod.',
  [Structure.LaAppendage]: 'orejuela',
  [Structure.PulmonaryVein]: 'v. pulmonar',
  [Structure.CoronarySinus]: 'SC',
  [Structure.PulmonaryArtery]: 'AP',
  [Structure.RvPapillary]: 'MP VD',
  [Structure.Svc]: 'VCS',
  [Structure.HepaticVein]: 'v. hepática',
  [Structure.Diaphragm]: 'diafragma',
};
