/**
 * GENERATED by tools/clinical/camus-compare.ts --surroundings-out (decision 144). Do not edit by hand: re-run the tool.
 *
 * What CAMUS apical images rated Good show around the left ventricle (src/clinical/surroundings.ts): near field,
 * far background, the bands outside each wall, the pericardial line and the transmural grey ratios; median,
 * interquartile range and 10th/90th percentiles across images. Side 1 is the septum (4CH) or the inferior wall
 * (2CH), side 2 the lateral or the anterior wall. Aggregate statistics only.
 *
 * Source: CAMUS — S. Leclerc et al., "Deep Learning for Segmentation Using an Open Large-Scale Dataset in 2D
 * Echocardiography", IEEE TMI 38(9):2198-2210, 2019, doi:10.1109/TMI.2019.2900516.
 */
import type { Quartiles } from './camusImageStats';
import type { SurroundingsMetric } from '../surroundings';

export const CAMUS_GOOD_SURROUNDINGS: Record<
  '4CH-ED' | '4CH-ES' | '2CH-ED' | '2CH-ES',
  Partial<Record<SurroundingsMetric, Quartiles>>
> = {
  '4CH-ED': {
    nearFieldGrey: { median: 104, p10: 60, p25: 83, p75: 122, p90: 136, n: 288 },
    farBackgroundGrey: { median: 79, p10: 47, p25: 62, p75: 95, p90: 121, n: 288 },
    farBackgroundP99: { median: 205, p10: 150, p25: 169, p75: 236, p90: 250, n: 288 },
    side1BandGrey: { median: 59, p10: 37, p25: 48, p75: 74, p90: 95, n: 288 },
    side2BandGrey: { median: 98, p10: 55, p25: 76, p75: 121, p90: 150, n: 285 },
    side1EpicardialPeakGrey: { median: 87, p10: 62, p25: 71, p75: 106, p90: 130, n: 288 },
    side2EpicardialPeakGrey: { median: 123, p10: 60, p25: 94, p75: 149, p90: 174, n: 288 },
    side1EndoOverMid: { median: 0.84, p10: 0.66, p25: 0.74, p75: 0.92, p90: 1.02, n: 288 },
    side1EpiOverMid: { median: 0.69, p10: 0.56, p25: 0.63, p75: 0.81, p90: 0.99, n: 288 },
    side2EndoOverMid: { median: 0.8, p10: 0.63, p25: 0.72, p75: 0.88, p90: 0.97, n: 286 },
    side2EpiOverMid: { median: 1.18, p10: 0.72, p25: 0.99, p75: 1.38, p90: 1.54, n: 286 },
  },
  '4CH-ES': {
    nearFieldGrey: { median: 104, p10: 60, p25: 82, p75: 122, p90: 137, n: 288 },
    farBackgroundGrey: { median: 71, p10: 47, p25: 56, p75: 89, p90: 110, n: 288 },
    farBackgroundP99: { median: 194, p10: 137, p25: 159, p75: 227, p90: 246, n: 288 },
    side1BandGrey: { median: 69, p10: 45, p25: 55, p75: 83, p90: 105, n: 288 },
    side2BandGrey: { median: 115, p10: 77, p25: 91, p75: 135, p90: 159, n: 288 },
    side1EpicardialPeakGrey: { median: 99, p10: 71, p25: 84, p75: 117, p90: 139, n: 288 },
    side2EpicardialPeakGrey: { median: 139, p10: 99, p25: 120, p75: 165, p90: 189, n: 288 },
    side1EndoOverMid: { median: 0.78, p10: 0.61, p25: 0.69, p75: 0.87, p90: 0.99, n: 288 },
    side1EpiOverMid: { median: 0.76, p10: 0.62, p25: 0.68, p75: 0.87, p90: 1.1, n: 288 },
    side2EndoOverMid: { median: 0.76, p10: 0.6, p25: 0.67, p75: 0.86, p90: 0.97, n: 288 },
    side2EpiOverMid: { median: 1.14, p10: 0.81, p25: 0.95, p75: 1.37, p90: 1.57, n: 288 },
  },
  '2CH-ED': {
    nearFieldGrey: { median: 115, p10: 75, p25: 95, p75: 134, p90: 150, n: 217 },
    farBackgroundGrey: { median: 78, p10: 41, p25: 60, p75: 98, p90: 118, n: 217 },
    farBackgroundP99: { median: 188, p10: 139, p25: 165, p75: 224, p90: 243, n: 217 },
    side1BandGrey: { median: 106, p10: 67, p25: 87, p75: 135, p90: 169, n: 215 },
    side2BandGrey: { median: 75, p10: 41, p25: 53, p75: 98, p90: 122, n: 211 },
    side1EpicardialPeakGrey: { median: 143, p10: 88, p25: 118, p75: 174, p90: 209, n: 217 },
    side2EpicardialPeakGrey: { median: 84, p10: 0, p25: 53, p75: 113, p90: 136, n: 217 },
    side1EndoOverMid: { median: 0.84, p10: 0.65, p25: 0.74, p75: 0.93, p90: 1.06, n: 217 },
    side1EpiOverMid: { median: 0.97, p10: 0.75, p25: 0.84, p75: 1.12, p90: 1.24, n: 217 },
    side2EndoOverMid: { median: 0.88, p10: 0.69, p25: 0.79, p75: 0.97, p90: 1.09, n: 214 },
    side2EpiOverMid: { median: 1.01, p10: 0.68, p25: 0.87, p75: 1.2, p90: 1.38, n: 214 },
  },
  '2CH-ES': {
    nearFieldGrey: { median: 116, p10: 75, p25: 93, p75: 134, p90: 149, n: 217 },
    farBackgroundGrey: { median: 72, p10: 39, p25: 53, p75: 93, p90: 108, n: 217 },
    farBackgroundP99: { median: 177, p10: 124, p25: 147, p75: 208, p90: 238, n: 217 },
    side1BandGrey: { median: 107, p10: 67, p25: 87, p75: 129, p90: 159, n: 217 },
    side2BandGrey: { median: 84, p10: 49, p25: 65, p75: 108, p90: 131, n: 212 },
    side1EpicardialPeakGrey: { median: 149, p10: 98, p25: 124, p75: 174, p90: 204, n: 217 },
    side2EpicardialPeakGrey: { median: 108, p10: 66, p25: 86, p75: 137, p90: 162, n: 217 },
    side1EndoOverMid: { median: 0.85, p10: 0.64, p25: 0.73, p75: 0.97, p90: 1.13, n: 217 },
    side1EpiOverMid: { median: 1.04, p10: 0.85, p25: 0.94, p75: 1.16, p90: 1.31, n: 217 },
    side2EndoOverMid: { median: 0.82, p10: 0.63, p25: 0.7, p75: 0.95, p90: 1.07, n: 215 },
    side2EpiOverMid: { median: 1.09, p10: 0.84, p25: 0.93, p75: 1.28, p90: 1.47, n: 215 },
  },
};
