/**
 * GENERATED by tools/clinical/camus-compare.ts --reference-out (decision 70). Do not edit by hand: re-run the tool.
 *
 * Displayed grey-level statistics of CAMUS apical images rated Good — the optimal window — per view and phase:
 * median, interquartile range and 10th/90th percentiles across images of each per-image statistic in
 * src/clinical/regionStats.ts (region medians after a 2-pixel erosion, contrast = myocardium − cavity, 5×5 local
 * std, speckle cell by ACF).
 * 500 patients read, 0 frames rejected by the label check. Aggregate statistics only.
 *
 * Source: CAMUS — S. Leclerc et al., "Deep Learning for Segmentation Using an Open Large-Scale Dataset in 2D
 * Echocardiography", IEEE TMI 38(9):2198-2210, 2019, doi:10.1109/TMI.2019.2900516.
 */
export interface Quartiles {
  median: number;
  p10: number;
  p25: number;
  p75: number;
  p90: number;
  n: number;
}

export type CamusMetric = 'cavityGrey' | 'myocardiumGrey' | 'atriumGrey' | 'contrast' | 'myocardialLocalStd' | 'speckleCellHorizontalMm' | 'speckleCellVerticalMm';

export const CAMUS_GOOD: Record<'4CH-ED' | '4CH-ES' | '2CH-ED' | '2CH-ES', Record<CamusMetric, Quartiles>> = {
  '4CH-ED': {
    cavityGrey: { median: 56, p10: 38, p25: 46, p75: 69, p90: 84, n: 288 },
    myocardiumGrey: { median: 97, p10: 73, p25: 84, p75: 112, p90: 127, n: 288 },
    atriumGrey: { median: 91, p10: 55, p25: 70, p75: 117, p90: 154, n: 288 },
    contrast: { median: 40, p10: 27, p25: 33, p75: 47, p90: 53, n: 288 },
    myocardialLocalStd: { median: 9.96, p10: 8.67, p25: 9.27, p75: 10.83, p90: 12, n: 288 },
    speckleCellHorizontalMm: { median: 2.09, p10: 1.74, p25: 1.87, p75: 2.31, p90: 2.64, n: 288 },
    speckleCellVerticalMm: { median: 1.91, p10: 1.52, p25: 1.68, p75: 2.22, p90: 2.6, n: 288 },
  },
  '4CH-ES': {
    cavityGrey: { median: 58, p10: 40, p25: 47, p75: 72, p90: 86, n: 288 },
    myocardiumGrey: { median: 102, p10: 79, p25: 89, p75: 116, p90: 132, n: 288 },
    atriumGrey: { median: 60, p10: 36, p25: 48, p75: 78, p90: 97, n: 288 },
    contrast: { median: 43, p10: 30, p25: 36, p75: 49, p90: 57, n: 288 },
    myocardialLocalStd: { median: 10.21, p10: 8.86, p25: 9.5, p75: 11.3, p90: 12.62, n: 288 },
    speckleCellHorizontalMm: { median: 2.26, p10: 1.8, p25: 2.03, p75: 2.53, p90: 2.97, n: 288 },
    speckleCellVerticalMm: { median: 1.87, p10: 1.5, p25: 1.67, p75: 2.24, p90: 2.58, n: 288 },
  },
  '2CH-ED': {
    cavityGrey: { median: 58, p10: 37, p25: 45, p75: 71, p90: 89, n: 217 },
    myocardiumGrey: { median: 102, p10: 75, p25: 89, p75: 117, p90: 134, n: 217 },
    atriumGrey: { median: 82, p10: 50, p25: 65, p75: 109, p90: 133, n: 216 },
    contrast: { median: 44, p10: 30, p25: 36, p75: 53, p90: 62, n: 217 },
    myocardialLocalStd: { median: 9.36, p10: 8.17, p25: 8.75, p75: 10.1, p90: 11.01, n: 217 },
    speckleCellHorizontalMm: { median: 2.37, p10: 1.95, p25: 2.14, p75: 2.64, p90: 3.01, n: 217 },
    speckleCellVerticalMm: { median: 2.44, p10: 1.82, p25: 2.07, p75: 2.88, p90: 3.32, n: 217 },
  },
  '2CH-ES': {
    cavityGrey: { median: 60, p10: 39, p25: 47, p75: 74, p90: 88, n: 217 },
    myocardiumGrey: { median: 106, p10: 79, p25: 91, p75: 120, p90: 136, n: 217 },
    atriumGrey: { median: 61, p10: 32, p25: 43, p75: 79, p90: 98, n: 217 },
    contrast: { median: 44, p10: 31, p25: 38, p75: 51, p90: 59, n: 217 },
    myocardialLocalStd: { median: 9.88, p10: 8.65, p25: 9.14, p75: 10.76, p90: 11.82, n: 217 },
    speckleCellHorizontalMm: { median: 2.53, p10: 2.08, p25: 2.25, p75: 2.86, p90: 3.25, n: 217 },
    speckleCellVerticalMm: { median: 2.33, p10: 1.78, p25: 1.98, p75: 2.74, p90: 3.46, n: 217 },
  },
};
