/**
 * GENERATED by tools/clinical/camus-compare.ts --geometry-out (decision 92). Do not edit by hand: re-run the tool.
 *
 * Where the left ventricle sits in CAMUS apical images rated Good, against the sector (src/clinical/apicalGeometry.ts):
 * median, interquartile range and 10th/90th percentiles across images. Aggregate statistics only.
 *
 * Source: CAMUS — S. Leclerc et al., "Deep Learning for Segmentation Using an Open Large-Scale Dataset in 2D
 * Echocardiography", IEEE TMI 38(9):2198-2210, 2019, doi:10.1109/TMI.2019.2900516.
 */
import type { Quartiles } from './camusImageStats';

export type ApicalGeometryMetric = 'apexOffsetMm' | 'apexDepthMm' | 'axisTiltDeg' | 'septalRayAngleDeg' | 'lateralRayAngleDeg' | 'septalMinusLateralGrey';

export const CAMUS_GOOD_GEOMETRY: Record<'4CH-ED' | '4CH-ES' | '2CH-ED' | '2CH-ES', Partial<Record<ApicalGeometryMetric, Quartiles>>> = {
  '4CH-ED': {
    apexOffsetMm: { median: 0, p10: -6.62, p25: -3.85, p75: 3.24, p90: 6.63, n: 288 },
    apexDepthMm: { median: 27.41, p10: 20.33, p25: 23.41, p75: 31.73, p90: 35.73, n: 288 },
    axisTiltDeg: { median: 5.72, p10: -6.83, p25: 1.99, p75: 8.95, p90: 12.01, n: 288 },
    septalRayAngleDeg: { median: 21.06, p10: 10.7, p25: 15.05, p75: 27.02, p90: 33.72, n: 288 },
    lateralRayAngleDeg: { median: 16.73, p10: 10.16, p25: 12.5, p75: 20.57, p90: 25.01, n: 288 },
    septalMinusLateralGrey: { median: 35, p10: -50, p25: 13, p75: 53, p90: 68, n: 288 },
  },
  '4CH-ES': {
    apexOffsetMm: { median: 0.76, p10: -6.33, p25: -2.62, p75: 4.94, p90: 7.85, n: 288 },
    apexDepthMm: { median: 29.88, p10: 22.49, p25: 26.18, p75: 34.19, p90: 38.5, n: 288 },
    axisTiltDeg: { median: 3.9, p10: -5.11, p25: 0.3, p75: 6.9, p90: 9.83, n: 288 },
    septalRayAngleDeg: { median: 13.47, p10: 4.22, p25: 8.29, p75: 19.73, p90: 26.21, n: 288 },
    lateralRayAngleDeg: { median: 13.85, p10: 7.04, p25: 10.14, p75: 18.9, p90: 23.74, n: 288 },
    septalMinusLateralGrey: { median: 24, p10: -29, p25: 4, p75: 38, p90: 53, n: 288 },
  },
  '2CH-ED': {
    apexOffsetMm: { median: -6.79, p10: -13.41, p25: -10.18, p75: -3.72, p90: 0.14, n: 217 },
    apexDepthMm: { median: 24.63, p10: 18.48, p25: 20.94, p75: 28.96, p90: 33.26, n: 217 },
    axisTiltDeg: { median: 7.31, p10: 0.7, p25: 3.82, p75: 10.77, p90: 14.58, n: 217 },
  },
  '2CH-ES': {
    apexOffsetMm: { median: -3.7, p10: -12.31, p25: -7.69, p75: -0.93, p90: 2.76, n: 217 },
    apexDepthMm: { median: 26.8, p10: 21.25, p25: 23.72, p75: 32.34, p90: 36.96, n: 217 },
    axisTiltDeg: { median: 6.19, p10: 0.27, p25: 2.5, p75: 10.15, p90: 14.5, n: 217 },
  },
};
