/**
 * GENERATED by tools/clinical/camus-compare.ts --reference-out (decision 70). Do not edit by hand: re-run the tool.
 *
 * Displayed grey-level statistics of CAMUS apical images rated Good — the optimal window — per view and phase:
 * median and interquartile range across images of each per-image statistic in src/clinical/regionStats.ts
 * (region medians after a 2-pixel erosion, contrast = myocardium − cavity, 5×5 local std, speckle cell by ACF).
 * 500 patients read, 0 frames rejected by the label check. Aggregate statistics only.
 *
 * Source: CAMUS — S. Leclerc et al., "Deep Learning for Segmentation Using an Open Large-Scale Dataset in 2D
 * Echocardiography", IEEE TMI 38(9):2198-2210, 2019, doi:10.1109/TMI.2019.2900516.
 */
export interface Quartiles {
  median: number;
  p25: number;
  p75: number;
  n: number;
}

export type CamusMetric = 'cavityGrey' | 'myocardiumGrey' | 'atriumGrey' | 'contrast' | 'myocardialLocalStd' | 'speckleCellHorizontalMm' | 'speckleCellVerticalMm';

export const CAMUS_GOOD: Record<'4CH-ED' | '4CH-ES' | '2CH-ED' | '2CH-ES', Record<CamusMetric, Quartiles>> = {
  '4CH-ED': {
    cavityGrey: { median: 56, p25: 46, p75: 69, n: 288 },
    myocardiumGrey: { median: 97, p25: 84, p75: 112, n: 288 },
    atriumGrey: { median: 91, p25: 70, p75: 117, n: 288 },
    contrast: { median: 40, p25: 33, p75: 47, n: 288 },
    myocardialLocalStd: { median: 9.96, p25: 9.27, p75: 10.83, n: 288 },
    speckleCellHorizontalMm: { median: 2.09, p25: 1.87, p75: 2.31, n: 288 },
    speckleCellVerticalMm: { median: 1.91, p25: 1.68, p75: 2.22, n: 288 },
  },
  '4CH-ES': {
    cavityGrey: { median: 58, p25: 47, p75: 72, n: 288 },
    myocardiumGrey: { median: 102, p25: 89, p75: 116, n: 288 },
    atriumGrey: { median: 60, p25: 48, p75: 78, n: 288 },
    contrast: { median: 43, p25: 36, p75: 49, n: 288 },
    myocardialLocalStd: { median: 10.21, p25: 9.5, p75: 11.3, n: 288 },
    speckleCellHorizontalMm: { median: 2.26, p25: 2.03, p75: 2.53, n: 288 },
    speckleCellVerticalMm: { median: 1.87, p25: 1.67, p75: 2.24, n: 288 },
  },
  '2CH-ED': {
    cavityGrey: { median: 58, p25: 45, p75: 71, n: 217 },
    myocardiumGrey: { median: 102, p25: 89, p75: 117, n: 217 },
    atriumGrey: { median: 82, p25: 65, p75: 109, n: 216 },
    contrast: { median: 44, p25: 36, p75: 53, n: 217 },
    myocardialLocalStd: { median: 9.36, p25: 8.75, p75: 10.1, n: 217 },
    speckleCellHorizontalMm: { median: 2.37, p25: 2.14, p75: 2.64, n: 217 },
    speckleCellVerticalMm: { median: 2.44, p25: 2.07, p75: 2.88, n: 217 },
  },
  '2CH-ES': {
    cavityGrey: { median: 60, p25: 47, p75: 74, n: 217 },
    myocardiumGrey: { median: 106, p25: 91, p75: 120, n: 217 },
    atriumGrey: { median: 61, p25: 43, p75: 79, n: 217 },
    contrast: { median: 44, p25: 38, p75: 51, n: 217 },
    myocardialLocalStd: { median: 9.88, p25: 9.14, p75: 10.76, n: 217 },
    speckleCellHorizontalMm: { median: 2.53, p25: 2.25, p75: 2.86, n: 217 },
    speckleCellVerticalMm: { median: 2.33, p25: 1.98, p75: 2.74, n: 217 },
  },
};
