import type { CaseDefinitionInput } from './schema';

/** Case 1 — Normal adult, excellent acoustic window, sinus rhythm 65 bpm. */
export const normalExcellentCase: CaseDefinitionInput = {
  schemaVersion: 1,
  id: 'normal-excellent-window',
  title: 'Normal — ventana excelente, sinusal 65 lpm',
  seed: 101,
  history:
    'Paciente sintético de 32 años, sin antecedentes, evaluación por soplo funcional. Sin datos reales de paciente.',
  demographics: { ageYears: 32, sexForReference: 'male', heightCm: 176, weightKg: 72 },
  bodyHabitus: { chestWallThicknessCm: 2.0, chestWidthCm: 32, chestDepthCm: 21, ribSpacingCm: 2.6, intercostalWidthCm: 1.7 },
  rhythm: { type: 'sinus', heartRateBpm: 65, rrVariabilityPct: 2, pvcProbability: 0 },
  anatomy: {
    lv: { eddCm: 4.8, lengthEdCm: 8.6, ivsdCm: 0.9, lvpwdCm: 0.9, sphericity: 0.5, apexWallThicknessCm: 0.7 },
    la: { apDiameterCm: 3.5, volumeMl: 52 },
    rv: { basalDiameterCm: 3.4, lengthCm: 7.4, freeWallThicknessCm: 0.4 },
    ra: { volumeMl: 45 },
    aorta: { lvotDiameterCm: 2.1, annulusCm: 2.3, sinusCm: 3.2, ascendingCm: 3.0 },
    mitral: {
      annulusDiameterCm: 3.0,
      anteriorLeafletLengthCm: 2.4,
      posteriorLeafletLengthCm: 1.3,
      maxOpeningDeg: 70,
      calcification: 0,
      thickeningCm: 0.1,
      samSeverity: 0,
    },
    aorticValve: { maxOpeningFraction: 1, calcification: 0, cuspThicknessCm: 0.08, bicuspid: false },
    tricuspid: { annulusDiameterCm: 3.3 },
    ivc: { diameterCm: 1.7, collapsePct: 70 },
    pericardium: { effusionCm: 0 },
    heartPosition: {
      baseCm: { x: 0.5, y: 0.6, z: -7.8 },
      longAxis: { x: 0.68, y: -0.5, z: 0.52 },
      anterior: { x: 0.3, y: 0.55, z: 0.6 },
    },
    wallMotion: [],
  },
  physiology: {
    edvMl: 120,
    esvMl: 45,
    mapseCm: 1.4,
    tapseCm: 2.2,
    ePeakMps: 0.8,
    aPeakMps: 0.55,
    decelerationTimeMs: 180,
    ivrtMs: 75,
    ePrimeSeptalCmps: 11,
    ePrimeLateralCmps: 14,
    sPrimeTricuspidCmps: 13,
    contractility: 1,
  },
  hemodynamics: {
    systolicBpMmHg: 120,
    diastolicBpMmHg: 75,
    rapMmHg: 3,
    paspMmHg: 25,
    avEffectiveAreaCm2: 3.0,
    trPresent: true,
    regurgitation: {},
  },
  acousticWindow: {
    chestWallAttenuation: 0.1,
    lungOverlapCm: 0,
    clutterLevel: 0.1,
    obesityAttenuation: 0.05,
    emphysemaScatter: 0,
    cardiacRotationDeg: 0,
  },
  flowPrimitives: [
    { id: 'mv', site: 'mitral-inflow', enabled: true, turbulence: 0.04 },
    { id: 'lvot', site: 'lvot', enabled: true, turbulence: 0.04 },
    { id: 'av', site: 'aortic-valve', enabled: true, turbulence: 0.05 },
    { id: 'tv', site: 'tricuspid-inflow', enabled: true, turbulence: 0.04 },
    { id: 'rvot', site: 'rvot', enabled: true, turbulence: 0.04 },
    { id: 'tr', site: 'tr-jet', enabled: true, turbulence: 0.2 },
  ],
  artifacts: [
    { type: 'rib-shadow', intensity: 1, enabled: true },
    { type: 'lung-reverberation', intensity: 1, enabled: true },
    { type: 'near-field-clutter', intensity: 0.3, enabled: true },
  ],
  learningObjectives: [
    'Obtener PLAX con septum, pared posterior, válvula mitral, LVOT, válvula aórtica y AI alineados.',
    'Rotar 90° en sentido horario hacia PSAX y recorrer los niveles aórtico, mitral y papilar.',
    'Adquirir A4C con ápex verdadero y evitar acortamiento.',
    'Medir LVOT y VTI con un Doppler pulsado bien alineado.',
  ],
  requiredViews: [
    { viewId: 'plax', minScore: 70 },
    { viewId: 'psax-mv', minScore: 60 },
    { viewId: 'psax-pm', minScore: 60 },
    { viewId: 'a4c', minScore: 70 },
  ],
  requiredMeasurements: [
    { measurementId: 'lvot-diameter', tolerancePct: 10 },
    { measurementId: 'lv-edd', tolerancePct: 10 },
    { measurementId: 'lvot-vti', tolerancePct: 15 },
    { measurementId: 'mitral-e', tolerancePct: 15 },
  ],
  difficulty: 1,
  references: [
    { referenceId: 'ase-tte-2019', usage: 'protocolo de vistas y sitios de medición' },
    { referenceId: 'ase-eacvi-chamber-2015', usage: 'rangos normales de cavidades' },
  ],
  impressionTruth: [
    'Ventrículo izquierdo de dimensiones y función sistólica normales.',
    'Válvulas morfológica y funcionalmente normales.',
    'Sin derrame pericárdico.',
  ],
};
