import { describe, expect, it } from 'vitest';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { GLSL_HEART } from './glslHeart';
import { GLSL_THORAX } from './glslThorax';

/**
 * Drift guard for the hand-written GLSL port of the classifier (decision 154). The acoustic chain writes no number on
 * both sides (glslParity.test.ts), but the heart and thorax classifiers of glslHeart.ts and glslThorax.ts still repeat
 * numbers of src/simulator/anatomy by hand, and the only check that sees a difference, e2e/gpu-equivalence, runs in a
 * browser: changing 0.88 to 0.70 in one side kept every unit test green (panel of 2026-09-22). This test counts, for
 * each number written on both sides, how many times each side writes it: [anatomy, GLSL].
 *  - a number newly written on both sides fails (move it to a named constant that reaches the shader, a paramLayout
 *    parameter, or a function generated by `npm run glsl:gen`); the list may only shrink;
 *  - a count that changes fails, which is how an edit of one side alone shows up even for a number written many
 *    times (0.6 → 0.7 in one of the twelve GLSL 0.6s). An anatomy edit that adds or removes one of these numbers for
 *    another reason updates its count here, after checking that the shader needs no matching edit.
 * The header constants of the shader (`const float NAME = ...`, interpolated from TypeScript) and the `#define`s are
 * shared by construction and are not counted.
 */
const KNOWN_SHARED_CLASSIFIER_LITERALS: Record<string, [anatomy: number, glsl: number]> = {
  '1e-12': [3, 3], '1e-9': [8, 5], '0.000001': [7, 8], '0.001': [6, 3], '0.012': [1, 1], '0.02': [11, 3],
  '0.03': [3, 3], '0.035': [2, 1], '0.04': [4, 2], '0.045': [1, 1], '0.05': [17, 4], '0.06': [6, 1], '0.08': [3, 2],
  '0.09': [2, 1], '0.1': [32, 10], '0.11': [1, 1], '0.12': [23, 18], '0.15': [17, 4], '0.18': [9, 4], '0.2': [33, 10],
  '0.22': [8, 6], '0.28': [4, 2], '0.29': [1, 1], '0.3': [42, 16], '0.33': [1, 1], '0.35': [26, 6], '0.4': [32, 10],
  '0.45': [30, 6], '0.55': [18, 6], '0.6': [35, 12], '0.65': [9, 2], '0.68': [3, 1], '0.7': [28, 4], '0.72': [3, 1],
  '0.75': [6, 2], '0.8': [29, 6], '0.85': [16, 3], '0.88': [2, 1], '0.9': [42, 4], '0.95': [11, 4], '0.97': [4, 2],
  '0.98': [3, 3], '0.999': [3, 2], '1.0001': [2, 1], '1.1': [13, 6], '1.2': [10, 2], '1.3': [8, 2], '1.4': [8, 2],
  '1.5': [24, 1], '1.6': [17, 9], '1.7': [5, 1], '1.8': [7, 1], '2.1': [3, 1], '2.2': [13, 4], '2.3': [9, 3],
  '2.4': [5, 2], '2.5': [14, 1], '2.6': [10, 2], '2.9': [3, 1], '3.1': [3, 1], '3.5': [13, 3], '4.2': [3, 1],
  '5': [3, 4], '5.3': [1, 1], '6.1': [1, 1], '6.5': [3, 1], '7': [1, 2], '7.3': [1, 1], '8.5': [8, 1], '8.8': [1, 1],
  '9': [1, 3], '9.5': [1, 1], '9.7': [1, 1], '11.3': [1, 1], '14.2': [1, 1], '17.3': [1, 1], '1000': [10, 7],
  '1000000000': [1, 4],
}; // prettier-ignore

const TRIVIAL = new Set(['0.0', '0.5', '1.0', '2.0', '3.0', '4.0', '0.25', '255.0']);
const stripComments = (code: string) =>
  code.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');

/** Non-trivial numeric literals of a source, counted as TypeScript would print their value (`0.60` and `0.6` alike). */
function countLiterals(code: string, glsl: boolean, out: Map<string, number>): void {
  const body = stripComments(code)
    .split('\n')
    .filter(
      (l) =>
        !glsl ||
        !(/^\s*#define\b/.test(l) || /^\s*const\s+\w+\s+[A-Z][A-Z0-9_]*\s*(\[\d+\])?\s*=/.test(l)),
    )
    .join('\n');
  for (const m of body.matchAll(/(?<![\w.])-?\d+\.\d+(?:e-?\d+)?|(?<![\w.])-?\d+e-?\d+/g)) {
    const v = m[0].replace(/^-/, '');
    if (TRIVIAL.has(v)) continue;
    const key = String(Number(v));
    out.set(key, (out.get(key) ?? 0) + 1);
  }
}

function cpuClassifierSources(): string[] {
  const out: string[] = [];
  const walk = (dir: string) => {
    for (const name of readdirSync(dir)) {
      const p = join(dir, name);
      if (statSync(p).isDirectory()) walk(p);
      else if (name.endsWith('.ts') && !name.endsWith('.test.ts'))
        out.push(readFileSync(p, 'utf8'));
    }
  };
  walk(join(process.cwd(), 'src/simulator/anatomy'));
  return out;
}

describe('classifier: CPU ↔ GLSL literal drift guard', () => {
  const cpu = new Map<string, number>();
  for (const src of cpuClassifierSources()) countLiterals(src, false, cpu);
  const glsl = new Map<string, number>();
  countLiterals(GLSL_HEART, true, glsl);
  countLiterals(GLSL_THORAX, true, glsl);
  const shared = [...glsl.keys()].filter((v) => cpu.has(v));
  const known = new Map(
    Object.entries(KNOWN_SHARED_CLASSIFIER_LITERALS).map(([v, n]) => [String(Number(v)), n]),
  );

  it('writes no new number on both sides of the classifier', () => {
    const added = shared.filter((v) => !known.has(v)).sort();
    expect(
      added,
      'written in both src/simulator/anatomy and the GLSL classifier: share it through a constant or a generated function',
    ).toEqual([]);
  });

  it('keeps the count of every listed number on each side, so an edit of one side alone shows up', () => {
    const changed: string[] = [];
    for (const [v, [a, g]] of known) {
      const now: [number, number] = [cpu.get(v) ?? 0, glsl.get(v) ?? 0];
      if (now[0] !== a || now[1] !== g)
        changed.push(`'${v}': [${a}, ${g}] → [${now[0]}, ${now[1]}]`);
    }
    expect(
      changed,
      'a number of the classifier changed on one side: edit the other side too, or update [anatomy, GLSL] here (drop the entry when one side reaches 0)',
    ).toEqual([]);
  });
});
