// GENERATED by `npm run glsl:gen` (tools/glsl/ts2glsl.ts) from the TypeScript functions named below.
// Do not edit: change the TypeScript and regenerate. glslGenerated.test.ts fails when this file is stale.

/** Pure scalar functions shared by the CPU tracer and the shaders, transpiled from their TypeScript source. */
export const GLSL_GENERATED = /* glsl */ `
// src/simulator/anatomy/valveSkirt.ts: annulusOffset
float annulusOffset(float phi, float saddlePhi, float saddle) {
  float sn = sin(phi - saddlePhi);
  return saddle * (sn * sn - 0.5);
}
// src/simulator/anatomy/valveSkirt.ts: tvInflowTaper
float tvInflowTaper(float h, float close, float bulge) {
  if (h < -close) {
    return 2.0 * (-h - close);
  }
  if (h <= 0.0) {
    return 0.0;
  }
  float past = max(0.0, h - 1.6);
  return -bulge * min(1.0, h / 0.8) + 0.25 * past + 0.25 * past * past;
}
// src/simulator/anatomy/lvShape.ts: ellipseFactor
float ellipseFactor(float ratio, float az) {
  float c = cos(az);
  float s = sin(az) / ratio;
  return 1.0 / sqrt(c * c + s * s);
}
// src/simulator/anatomy/lvShape.ts: axialWallFactor
float axialWallFactor(float zeta, float apexFrac) {
  if (zeta <= 0.5) {
    return 1.0;
  }
  float u = min(1.0, (zeta - 0.5) / 0.5);
  return 1.0 - (1.0 - apexFrac) * u * u;
}
// src/simulator/anatomy/rv.ts: rvAxialTaper
float rvAxialTaper(float tvPlane, float zApex, float z) {
  if (z <= tvPlane) {
    return 0.85;
  }
  float q = min(1.0, (z - tvPlane) / max(0.5, zApex - tvPlane));
  float s = max(0.0, (q - 0.25) / 0.75);
  return (1.0 - 0.55 * s) * sqrt(max(0.0, 1.0 - s * s * s * s * s));
}
// src/simulator/anatomy/rv.ts: rvAzProfile
float rvAzProfile(float rvAzA, float rvAzP, float u) {
  float sn = sin(PI * u);
  float uIn = (PI + 0.04 - rvAzA) / (rvAzP - rvAzA);
  float inflow = exp(-((u - uIn) * (u - uIn)) / (2.0 * 0.18 * 0.18));
  return pow(min(1.0, max(0.0, sn) / 0.75), 0.7) * (0.85 + 0.15 * inflow);
}
// src/simulator/anatomy/rv.ts: rvFloorZ
float rvFloorZ(float tvCz, float tvZ, float pvZ, float u, float off) {
  float uInf = 0.35;
  if (u >= uInf) {
    return tvCz + tvZ + off;
  }
  float w = u / uInf;
  return tvCz + pvZ + (tvZ + off - pvZ) * w - 2.6 * (1.0 - w);
}
// src/simulator/anatomy/lvWall.ts: septalShiftAt
float septalShiftAt(float shiftCm, float az, float levelFrac) {
  if (shiftCm <= 0.0) {
    return 0.0;
  }
  float c = -cos(az);
  if (c <= 0.0) {
    return 0.0;
  }
  float zw = 1.0 - pow((levelFrac - 0.45) / 0.45, 2.0);
  if (zw <= 0.0) {
    return 0.0;
  }
  return shiftCm * c * c * zw;
}
// src/simulator/anatomy/classify/root.ts: rootBend
float rootBend(float t) {
  return t > 3.0 ? 0.16 * (t - 3.0) * (t - 3.0) : 0.0;
}
// src/simulator/anatomy/classify/atria.ts: atrialScale
float atrialScale(float booster, float reservoir, float contraction) {
  return booster * (reservoir + (1.0 - reservoir) * contraction);
}
// src/simulator/anatomy/classify/atria.ts: iasThickness
float iasThickness(float fo) {
  return fo < 1.0 ? 0.12 : fo < 1.3 ? 0.7 : 0.55;
}
// src/simulator/anatomy/classify/atria.ts: raCollapseScale
float raCollapseScale(float raCollapse) {
  return 1.0 - 0.35 * raCollapse;
}
// src/simulator/anatomy/classify/rightVentricle.ts: rvFreeWallNow
float rvFreeWallNow(float freeWallCm, float contraction) {
  return freeWallCm * (1.0 + 0.35 * contraction);
}
// src/simulator/anatomy/classify/rightVentricle.ts: rvOutflowScale
float rvOutflowScale(float contraction) {
  return 0.85 + 0.15 * (1.0 - contraction);
}
// src/simulator/renderer/acoustic/acoustics.ts: myoAnisoGain
float myoAnisoGain(float dphi, float dz2) {
  return (MYO_ANISO_FLOOR + (1.0 - MYO_ANISO_FLOOR) * (1.0 - MYO_HELIX_COS2 * dphi * dphi - (1.0 - MYO_HELIX_COS2) * dz2));
}
// src/simulator/renderer/acoustic/acoustics.ts: myoHelixGain
float myoHelixGain(float dphi, float dz, float u) {
  float alpha = ((MYO_HELIX_ENDO_DEG + (MYO_HELIX_EPI_DEG - MYO_HELIX_ENDO_DEG) * u) * PI) / 180.0;
  float c = cos(alpha) * dphi + sin(alpha) * dz;
  return MYO_ANISO_FLOOR + (1.0 - MYO_ANISO_FLOOR) * (1.0 - c * c);
}
// src/simulator/renderer/acoustic/acoustics.ts: pleuralReverberation
float pleuralReverberation(float rCm, float entryCm, float transmission, float modulation) {
  if (rCm <= entryCm) {
    return 0.0;
  }
  float d = rCm - entryCm;
  float period = max(entryCm, REVERB_PERIOD_MIN_CM);
  float k = d / period;
  float first = max(0.0, floor(k) - 1.0);
  float decay = pow(REVERB_DECAY, first + 1.0);
  float band = 0.0;
  for (int j = 0; j < 4; j++) {
    float offset = (d - (first + float(j)) * period) / REVERB_WIDTH_CM;
    band += decay * exp(-offset * offset);
    decay *= REVERB_DECAY;
  }
  float diffuse = REVERB_DIFFUSE * exp(-d / REVERB_DIFFUSE_DECAY_CM) * modulation;
  return transmission * (REVERB_GAIN * band + diffuse);
}
// src/simulator/renderer/acoustic/acoustics.ts: beamHalfWidthCm
float beamHalfWidthCm(float rCm, float focusCm) {
  float taper = 1.0 - rCm / max(1.0, focusCm);
  return (sqrt(FOCUS_HALF_APERTURE_MM * FOCUS_HALF_APERTURE_MM * taper * taper + FOCUS_WAIST_LATERAL_MM * FOCUS_WAIST_LATERAL_MM) / 10.0);
}
// src/simulator/renderer/acoustic/acoustics.ts: focusingGain
float focusingGain(float rCm, float focusCm) {
  float taper = 1.0 - rCm / max(1.0, focusCm);
  float wl = beamHalfWidthCm(rCm, focusCm) * 10.0;
  float we = sqrt(FOCUS_HALF_ELEVATION_MM * FOCUS_HALF_ELEVATION_MM * taper * taper + FOCUS_WAIST_ELEVATION_MM * FOCUS_WAIST_ELEVATION_MM);
  return sqrt((FOCUS_WAIST_LATERAL_MM / wl) * (FOCUS_WAIST_ELEVATION_MM / we));
}
// src/simulator/renderer/acoustic/acoustics.ts: membraneWeight
float membraneWeight(float normalDotPlane, float sliceHalfWidthCm) {
  float along = abs(normalDotPlane);
  return MEMBRANE_CM / (MEMBRANE_CM + 2.0 * sliceHalfWidthCm * along);
}
// src/simulator/renderer/acoustic/psf.ts: sliceHalfWidthCm
float sliceHalfWidthCm(float rCm, float focusCm) {
  return SLICE_HALF_BASE_CM + SLICE_HALF_SLOPE * abs(rCm - focusCm);
}
`;

/** Shader constants the generated functions read (must be #defines or constants of the including shader). */
export const GLSL_GENERATED_FREE_IDENTIFIERS: readonly string[] = ["FOCUS_HALF_APERTURE_MM","FOCUS_HALF_ELEVATION_MM","FOCUS_WAIST_ELEVATION_MM","FOCUS_WAIST_LATERAL_MM","MEMBRANE_CM","MYO_ANISO_FLOOR","MYO_HELIX_COS2","MYO_HELIX_ENDO_DEG","MYO_HELIX_EPI_DEG","REVERB_DECAY","REVERB_DIFFUSE","REVERB_DIFFUSE_DECAY_CM","REVERB_GAIN","REVERB_PERIOD_MIN_CM","REVERB_WIDTH_CM","SLICE_HALF_BASE_CM","SLICE_HALF_SLOPE"];
