import { describe, expect, it } from 'vitest';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { GLSL_HEART } from './glslHeart';
import { GLSL_THORAX } from './glslThorax';

/**
 * Drift guard for the hand-written GLSL port of the classifier (decision 154). The acoustic chain writes no number on
 * both sides (glslParity.test.ts), but the heart and thorax classifiers of glslHeart.ts and glslThorax.ts still repeat
 * numbers of src/simulator/anatomy by hand, and the only check that sees a difference, e2e/gpu-equivalence, runs in a
 * browser: changing 0.88 to 0.70 in one side kept every unit test green (panel of 2026-09-22). This test lists the
 * literals written on both sides. The list may only shrink:
 *  - a literal newly written on both sides fails (move it to a named constant that reaches the shader, a paramLayout
 *    parameter, or a function generated by `npm run glsl:gen`);
 *  - a listed literal that is no longer on both sides fails too, which is how an edit of one side alone shows up
 *    (remove it from the list if the copy was removed on purpose, on both sides).
 * The header constants of the shader (`const float NAME = ...`, interpolated from TypeScript) and the `#define`s are
 * shared by construction and are not counted.
 */
const KNOWN_SHARED_CLASSIFIER_LITERALS = [
  '1e-12', '1e-9', '0.000001', '0.001', '0.012', '0.02', '0.03', '0.035', '0.04', '0.045', '0.05', '0.06', '0.08',
  '0.09', '0.1', '0.11', '0.12', '0.15', '0.18', '0.2', '0.22', '0.28', '0.29', '0.3', '0.33', '0.35', '0.4', '0.45',
  '0.55', '0.6', '0.65', '0.68', '0.7', '0.72', '0.75', '0.8', '0.85', '0.88', '0.9', '0.95', '0.97', '0.98',
  '0.999', '1.0001', '1.1', '1.2', '1.3', '1.4', '1.5', '1.6', '1.7', '1.8', '2.1', '2.2', '2.3', '2.4', '2.5', '2.6',
  '2.9', '3.1', '3.5', '4.2', '5', '5.3', '6.1', '6.5', '7', '7.3', '8.5', '8.8', '9', '9.5', '9.7', '11.3', '14.2',
  '17.3', '1000', '1000000000',
]; // prettier-ignore

const TRIVIAL = new Set(['0.0', '0.5', '1.0', '2.0', '3.0', '4.0', '0.25', '255.0']);
const stripComments = (code: string) =>
  code.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');

/** Non-trivial numeric literals of a source, as TypeScript would print their value (`0.60` and `0.6` alike). */
function literals(code: string, glsl: boolean): Set<string> {
  const out = new Set<string>();
  const body = stripComments(code)
    .split('\n')
    .filter(
      (l) =>
        !glsl ||
        !(/^\s*#define\b/.test(l) || /^\s*const\s+\w+\s+[A-Z][A-Z0-9_]*\s*(\[\d+\])?\s*=/.test(l)),
    )
    .join('\n');
  for (const m of body.matchAll(/(?<![\w.])-?\d+\.\d+(?:e-?\d+)?|(?<![\w.])-?\d+e-?\d+/g)) {
    const v = m[0].replace(/^-/, '');
    if (!TRIVIAL.has(v)) out.add(String(Number(v)));
  }
  return out;
}

function cpuClassifierSources(): string[] {
  const out: string[] = [];
  const walk = (dir: string) => {
    for (const name of readdirSync(dir)) {
      const p = join(dir, name);
      if (statSync(p).isDirectory()) walk(p);
      else if (name.endsWith('.ts') && !name.endsWith('.test.ts'))
        out.push(readFileSync(p, 'utf8'));
    }
  };
  walk(join(process.cwd(), 'src/simulator/anatomy'));
  return out;
}

describe('classifier: CPU ↔ GLSL literal drift guard', () => {
  const cpu = new Set<string>();
  for (const s of cpuClassifierSources()) for (const v of literals(s, false)) cpu.add(v);
  const glsl = new Set([...literals(GLSL_HEART, true), ...literals(GLSL_THORAX, true)]);
  const shared = [...glsl].filter((v) => cpu.has(v));
  const known = new Set(KNOWN_SHARED_CLASSIFIER_LITERALS.map((v) => String(Number(v))));

  it('writes no new number on both sides of the classifier', () => {
    const added = shared.filter((v) => !known.has(v)).sort();
    expect(
      added,
      'written in both src/simulator/anatomy and the GLSL classifier: share it through a constant or a generated function',
    ).toEqual([]);
  });

  it('keeps every listed copy on both sides, so an edit of one side alone shows up', () => {
    const stale = [...known].filter((v) => !shared.includes(v)).sort();
    expect(
      stale,
      'listed as written on both sides but now on one side only: edit the other side too, or drop the entry if both copies went',
    ).toEqual([]);
  });
});
