// GENERATED by `npm run glsl:gen` (tools/glsl/ts2glsl.ts) from the TypeScript functions named below.
// Do not edit: change the TypeScript and regenerate. glslGenerated.test.ts fails when this file is stale.

/** Pure scalar functions shared by the CPU tracer and the shaders, transpiled from their TypeScript source. */
export const GLSL_GENERATED = /* glsl */ `
// src/simulator/anatomy/valveSkirt.ts: saddleOffset
float saddleOffset(float phi, float phiA, float saddle) {
  float sn = sin(phi - phiA);
  return saddle * sn * sn;
}
// src/simulator/anatomy/lvShape.ts: ellipseFactor
float ellipseFactor(float ratio, float az) {
  float c = cos(az);
  float s = sin(az) / ratio;
  return 1.0 / sqrt(c * c + s * s);
}
// src/simulator/anatomy/lvShape.ts: axialWallFactor
float axialWallFactor(float zeta, float apexFrac) {
  if (zeta <= 0.5) {
    return 1.0;
  }
  float u = min(1.0, (zeta - 0.5) / 0.5);
  return 1.0 - (1.0 - apexFrac) * u * u;
}
// src/simulator/anatomy/rv.ts: rvAxialTaper
float rvAxialTaper(float tvPlane, float zApex, float z) {
  if (z <= tvPlane) {
    return 0.85;
  }
  float q = min(1.0, (z - tvPlane) / max(0.5, zApex - tvPlane));
  float s = max(0.0, (q - 0.25) / 0.75);
  return (1.0 - 0.55 * s) * sqrt(max(0.0, 1.0 - s * s * s * s * s));
}
// src/simulator/anatomy/lvWall.ts: septalShiftAt
float septalShiftAt(float shiftCm, float az, float levelFrac) {
  if (shiftCm <= 0.0) {
    return 0.0;
  }
  float c = -cos(az);
  if (c <= 0.0) {
    return 0.0;
  }
  float zw = 1.0 - pow((levelFrac - 0.45) / 0.45, 2.0);
  if (zw <= 0.0) {
    return 0.0;
  }
  return shiftCm * c * c * zw;
}
// src/simulator/renderer/acoustic/acoustics.ts: myoAnisoGain
float myoAnisoGain(float dphi, float dz2) {
  return (MYO_ANISO_FLOOR + (1.0 - MYO_ANISO_FLOOR) * (1.0 - MYO_HELIX_COS2 * dphi * dphi - (1.0 - MYO_HELIX_COS2) * dz2));
}
// src/simulator/renderer/acoustic/acoustics.ts: pleuralReverberation
float pleuralReverberation(float rCm, float entryCm, float transmission, float modulation) {
  if (rCm <= entryCm) {
    return 0.0;
  }
  float d = rCm - entryCm;
  float period = max(entryCm, REVERB_PERIOD_MIN_CM);
  float k = d / period;
  float first = max(0.0, floor(k) - 1.0);
  float decay = pow(REVERB_DECAY, first + 1.0);
  float band = 0.0;
  for (int j = 0; j < 4; j++) {
    float offset = (d - (first + float(j)) * period) / REVERB_WIDTH_CM;
    band += decay * exp(-offset * offset);
    decay *= REVERB_DECAY;
  }
  float diffuse = REVERB_DIFFUSE * pow(REVERB_DECAY, k + 1.0) * modulation;
  return transmission * (REVERB_GAIN * band + diffuse);
}
// src/simulator/renderer/acoustic/psf.ts: sliceHalfWidthCm
float sliceHalfWidthCm(float rCm, float focusCm) {
  return SLICE_HALF_BASE_CM + SLICE_HALF_SLOPE * abs(rCm - focusCm);
}
`;

/** Shader constants the generated functions read (must be #defines or constants of the including shader). */
export const GLSL_GENERATED_FREE_IDENTIFIERS: readonly string[] = ["MYO_ANISO_FLOOR","MYO_HELIX_COS2","REVERB_DECAY","REVERB_DIFFUSE","REVERB_GAIN","REVERB_PERIOD_MIN_CM","REVERB_WIDTH_CM","SLICE_HALF_BASE_CM","SLICE_HALF_SLOPE"];
