// GENERATED by `npm run glsl:gen` (tools/glsl/ts2glsl.ts) from the TypeScript functions named below.
// Do not edit: change the TypeScript and regenerate. glslGenerated.test.ts fails when this file is stale.

/** Pure scalar functions shared by the CPU tracer and the shaders, transpiled from their TypeScript source. */
export const GLSL_GENERATED = /* glsl */ `
// src/simulator/anatomy/valveSkirt.ts: annulusOffset
float annulusOffset(float phi, float saddlePhi, float saddle, float tiltC, float tiltS, float lift) {
  float sn = sin(phi - saddlePhi);
  return saddle * (sn * sn - 0.5) + tiltC * cos(phi) + tiltS * sin(phi) + lift;
}
// src/simulator/anatomy/valveSkirt.ts: tvInflowTaper
float tvInflowTaper(float h, float close, float bulge) {
  if (h < -close) {
    return 2.0 * (-h - close);
  }
  if (h <= 0.0) {
    return 0.0;
  }
  float past = max(0.0, h - 1.6);
  return -bulge * min(1.0, h / 0.8) + 0.25 * past + 0.25 * past * past;
}
// src/simulator/anatomy/lvShape.ts: ellipseFactor
float ellipseFactor(float ratio, float az) {
  float c = cos(az);
  float s = sin(az) / ratio;
  return 1.0 / sqrt(c * c + s * s);
}
// src/simulator/anatomy/lvShape.ts: axialWallFactor
float axialWallFactor(float zeta, float apexFrac) {
  if (zeta <= 0.5) {
    return 1.0;
  }
  float u = min(1.0, (zeta - 0.5) / 0.5);
  return 1.0 - (1.0 - apexFrac) * u * u;
}
// src/simulator/anatomy/lvShape.ts: lvNeckWeight
float lvNeckWeight(float zeta) {
  if (zeta >= LV_NECK_ZETA) {
    return 0.0;
  }
  if (zeta <= 0.0) {
    return 1.0;
  }
  float u = 1.0 - zeta / LV_NECK_ZETA;
  return u * u;
}
// src/simulator/anatomy/rv.ts: rvAxialTaper
float rvAxialTaper(float tvPlane, float zApex, float z) {
  if (z <= tvPlane) {
    float a = min(1.0, (tvPlane - z) / 1.5);
    return 1.0 - 0.15 * a * a * (3.0 - 2.0 * a);
  }
  float q = min(1.0, (z - tvPlane) / max(0.5, zApex - tvPlane));
  float s = max(0.0, (q - 0.25) / 0.75);
  return (1.0 - 0.55 * s) * sqrt(max(0.0, 1.0 - s * s * s * s * s));
}
// src/simulator/anatomy/rv.ts: rvAzProfile
float rvAzProfile(float rvAzA, float rvAzP, float u) {
  float sn = sin(PI * u);
  float uIn = (PI + 0.04 - rvAzA) / (rvAzP - rvAzA);
  float inflow = exp(-((u - uIn) * (u - uIn)) / (2.0 * 0.18 * 0.18));
  return pow(min(1.0, max(0.0, sn) / 0.75), 0.7) * (0.85 + 0.15 * inflow);
}
// src/simulator/anatomy/rv.ts: rvFloorZ
float rvFloorZ(float tvCz, float tvZ, float pvZ, float u, float off) {
  float uInf = 0.35;
  if (u >= uInf) {
    return tvCz + tvZ + off;
  }
  float w = u / uInf;
  return tvCz + pvZ + (tvZ + off - pvZ) * w - 2.6 * (1.0 - w);
}
// src/simulator/anatomy/rv.ts: rvRadialContraction
float rvRadialContraction(float u) {
  float s = min(1.0, max(0.0, (u - 0.15) / 0.35));
  return 0.15 + (RV_BODY_RADIAL_CONTRACTION - 0.15) * s * s * (3.0 - 2.0 * s);
}
// src/simulator/anatomy/lvWall.ts: septalShiftAt
float septalShiftAt(float shiftCm, float az, float levelFrac) {
  if (shiftCm <= 0.0) {
    return 0.0;
  }
  float c = -cos(az);
  if (c <= 0.0) {
    return 0.0;
  }
  float zw = 1.0 - (((levelFrac - 0.45) / 0.45) * ((levelFrac - 0.45) / 0.45));
  if (zw <= 0.0) {
    return 0.0;
  }
  return shiftCm * c * c * zw;
}
// src/simulator/anatomy/lvWall.ts: septalCrestFactor
float septalCrestFactor(float az, float zRel) {
  float da = abs(az - SEPTAL_CREST_AZ);
  if (da > PI) {
    da = 2.0 * PI - da;
  }
  if (da >= SEPTAL_CREST_HALF_WIDTH) {
    return 1.0;
  }
  float cw = cos((da / SEPTAL_CREST_HALF_WIDTH) * (PI / 2.0));
  float d = zRel - SEPTAL_CREST_Z_CM;
  float f = 1.0;
  if (d <= 0.0) {
    f = 0.2;
  } else {
    if (d < 0.1) {
      f = 0.2 + 1.1 * d;
    } else {
      if (d < 0.2) {
        f = 0.31 + 1.2 * (d - 0.1);
      } else {
        if (d < 0.5) {
          f = 0.43 + 0.7 * (d - 0.2);
        } else {
          if (d < 1.0) {
            f = 0.64 + 0.72 * (d - 0.5);
          }
        }
      }
    }
  }
  return 1.0 - cw * cw * (1.0 - f);
}
// src/simulator/anatomy/lvSegments.ts: lvSegmentCode
float lvSegmentCode(float azimuthRad, float levelFrac, float rvAzA, float rvAzP) {
  float septal = (rvAzA + rvAzP) * 0.5;
  float raw = ((azimuthRad - septal) * 180.0) / PI + 180.0;
  float deg = raw - 360.0 * floor(raw / 360.0);
  if (deg >= 360.0) {
    deg = 0.0;
  }
  float quadrant = 15.0;
  if (deg < 45.0 || deg >= 315.0) {
    quadrant = 16.0;
  } else {
    if (deg < 135.0) {
      quadrant = 13.0;
    } else {
      if (deg < 225.0) {
        quadrant = 14.0;
      }
    }
  }
  if (levelFrac >= 1.0) {
    return quadrant + 4.0;
  }
  if (levelFrac >= 2.0 / 3.0) {
    return quadrant;
  }
  float base = levelFrac < 1.0 / 3.0 ? 0.0 : 6.0;
  if (deg < 60.0) {
    return base + 6.0;
  }
  if (deg < 120.0) {
    return base + 1.0;
  }
  if (deg < 180.0) {
    return base + 2.0;
  }
  if (deg < 240.0) {
    return base + 3.0;
  }
  if (deg < 300.0) {
    return base + 4.0;
  }
  return base + 5.0;
}
// src/simulator/anatomy/lvSegments.ts: lvWallKind
float lvWallKind(float code) {
  float c = code >= 17.0 ? code - 4.0 : code;
  if (c == 2.0 || c == 3.0 || c == 8.0 || c == 9.0 || c == 14.0) {
    return 1.0;
  }
  if (c == 1.0 || c == 7.0 || c == 13.0) {
    return 2.0;
  }
  if (c == 4.0 || c == 5.0 || c == 10.0 || c == 11.0 || c == 15.0) {
    return 3.0;
  }
  return 0.0;
}
// src/simulator/anatomy/classify/root.ts: rootBend
float rootBend(float t) {
  return t > 3.0 ? 0.16 * (t - 3.0) * (t - 3.0) : 0.0;
}
// src/simulator/anatomy/thoraxModel.ts: mediastinumDistance
float mediastinumDistance(float x, float y, float z) {
  float px = (x + 0.5) / 1.8;
  float pz = (z + 15.5) / 4.0;
  float posterior = px * px + pz * pz - 1.0;
  float u = min(1.0, max(0.0, (y - 2.0) / 4.0));
  float halfWidth = 2.5 * u * u * (3.0 - 2.0 * u);
  float superior = 1.0;
  if (halfWidth > 0.05) {
    float sx = (x + 0.5) / halfWidth;
    float sz = (z + 8.0) / 5.0;
    superior = sx * sx + sz * sz - 1.0;
  }
  float rs = DESC_AORTA_R + DESC_AORTA_WALL + DESC_AORTA_SLEEVE;
  float ax = (x - DESC_AORTA_X) / rs;
  float az = (z - DESC_AORTA_Z - DESC_AORTA_SLEEVE_FORWARD) / (rs + DESC_AORTA_SLEEVE_FORWARD);
  float aorta = ax * ax + az * az - 1.0;
  return min(min(posterior, superior), aorta);
}
// src/simulator/anatomy/classify/atria.ts: atrialScale
float atrialScale(float booster, float reservoir, float contraction) {
  return booster * (reservoir + (1.0 - reservoir) * contraction);
}
// src/simulator/anatomy/classify/atria.ts: iasThickness
float iasThickness(float fo) {
  return fo < 1.0 ? 0.12 : fo < 1.3 ? 0.7 : 0.55;
}
// src/simulator/anatomy/classify/atria.ts: raCollapseScale
float raCollapseScale(float raCollapse) {
  return 1.0 - 0.35 * raCollapse;
}
// src/simulator/anatomy/classify/rightVentricle.ts: rvFreeWallNow
float rvFreeWallNow(float freeWallCm, float contraction) {
  return freeWallCm * (1.0 + 0.35 * contraction);
}
// src/simulator/anatomy/classify/rightVentricle.ts: rvOutflowScale
float rvOutflowScale(float contraction) {
  return 0.85 + 0.15 * (1.0 - contraction);
}
// src/simulator/renderer/acoustic/acoustics.ts: myoHelixGain
float myoHelixGain(float dphi, float dz, float u) {
  float alpha = ((MYO_HELIX_ENDO_DEG + (MYO_HELIX_EPI_DEG - MYO_HELIX_ENDO_DEG) * u) * PI) / 180.0;
  float c = cos(alpha) * dphi + sin(alpha) * dz;
  return MYO_ANISO_FLOOR + (1.0 - MYO_ANISO_FLOOR) * (1.0 - c * c);
}
// src/simulator/renderer/acoustic/acoustics.ts: pleuralReverberation
float pleuralReverberation(float rCm, float entryCm, float transmission, float modulation, float coherence) {
  if (rCm <= entryCm) {
    return 0.0;
  }
  float d = rCm - entryCm;
  float period = max(entryCm, REVERB_PERIOD_MIN_CM);
  float k = d / period;
  float first = max(0.0, floor(k) - 1.0);
  float decay = pow(REVERB_DECAY, first + 1.0);
  float band = 0.0;
  for (int j = 0; j < 4; j++) {
    float offset = (d - (first + float(j)) * period) / REVERB_WIDTH_CM;
    band += decay * exp(-offset * offset);
    decay *= REVERB_DECAY;
  }
  float diffuse = REVERB_DIFFUSE * exp(-d / REVERB_DIFFUSE_DECAY_CM) * modulation;
  return transmission * (REVERB_GAIN * band * coherence + diffuse);
}
// src/simulator/renderer/acoustic/acoustics.ts: pleuralIncidenceCos
float pleuralIncidenceCos(float dEntryCm, float arcCm) {
  return arcCm / sqrt(arcCm * arcCm + dEntryCm * dEntryCm);
}
// src/simulator/renderer/acoustic/acoustics.ts: pleuralCoherence
float pleuralCoherence(float c) {
  return c * c * c * c;
}
// src/simulator/renderer/acoustic/acoustics.ts: beamHalfWidthCm
float beamHalfWidthCm(float rCm, float focusCm) {
  float taper = 1.0 - rCm / max(1.0, focusCm);
  return (sqrt(FOCUS_HALF_APERTURE_MM * FOCUS_HALF_APERTURE_MM * taper * taper + FOCUS_WAIST_LATERAL_MM * FOCUS_WAIST_LATERAL_MM) / 10.0);
}
// src/simulator/renderer/acoustic/acoustics.ts: focusingGain
float focusingGain(float rCm, float focusCm) {
  float taper = 1.0 - rCm / max(1.0, focusCm);
  float wl = beamHalfWidthCm(rCm, focusCm) * 10.0;
  float we = sqrt(FOCUS_HALF_ELEVATION_MM * FOCUS_HALF_ELEVATION_MM * taper * taper + FOCUS_WAIST_ELEVATION_MM * FOCUS_WAIST_ELEVATION_MM);
  return sqrt((FOCUS_WAIST_LATERAL_MM / wl) * (FOCUS_WAIST_ELEVATION_MM / we));
}
// src/simulator/renderer/acoustic/acoustics.ts: membraneWeight
float membraneWeight(float normalDotPlane, float sliceHalfWidthCm) {
  float along = abs(normalDotPlane);
  return MEMBRANE_CM / (MEMBRANE_CM + 2.0 * sliceHalfWidthCm * along);
}
// src/simulator/renderer/acoustic/psf.ts: sliceHalfWidthCm
float sliceHalfWidthCm(float rCm, float focusCm) {
  return SLICE_HALF_BASE_CM + SLICE_HALF_SLOPE * abs(rCm - focusCm);
}
`;

/** Shader constants the generated functions read (must be #defines or constants of the including shader). */
export const GLSL_GENERATED_FREE_IDENTIFIERS: readonly string[] = ["DESC_AORTA_R","DESC_AORTA_SLEEVE","DESC_AORTA_SLEEVE_FORWARD","DESC_AORTA_WALL","DESC_AORTA_X","DESC_AORTA_Z","FOCUS_HALF_APERTURE_MM","FOCUS_HALF_ELEVATION_MM","FOCUS_WAIST_ELEVATION_MM","FOCUS_WAIST_LATERAL_MM","LV_NECK_ZETA","MEMBRANE_CM","MYO_ANISO_FLOOR","MYO_HELIX_ENDO_DEG","MYO_HELIX_EPI_DEG","REVERB_DECAY","REVERB_DIFFUSE","REVERB_DIFFUSE_DECAY_CM","REVERB_GAIN","REVERB_PERIOD_MIN_CM","REVERB_WIDTH_CM","RV_BODY_RADIAL_CONTRACTION","SEPTAL_CREST_AZ","SEPTAL_CREST_HALF_WIDTH","SEPTAL_CREST_Z_CM","SLICE_HALF_BASE_CM","SLICE_HALF_SLOPE"];
